spring:
     application:
          name: ${NOMBRE_MICROSERVICIO:vg-ms-distribution}
     data:
          mongodb:
               uri: mongodb+srv://${MONGO_USERNAME:sistemajass}:${MONGO_PASSWORD:ZC7O1Ok40SwkfEje}@sistemajass.jn6cpoz.mongodb.net/${MONGO_DATABASE:JASS_DIGITAL}?retryWrites=true&w=majority
     web:
          resources:
               cache:
                    period: 0
     security:
          oauth2:
               resourceserver:
                    jwt:
                         issuer-uri: https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass
                         jwk-set-uri: https://lab.vallegrande.edu.pe/jass/keycloak/realms/sistema-jass/protocol/openid-connect/certs

# =============================================================================
# CONFIGURACIÓN DEL SERVIDOR
# =============================================================================
server:
     port: 8086
     servlet:
          context-path: /jass/ms-distribution
     forward-headers-strategy: framework

# =============================================================================
# CONFIGURACIÓN DE SEGURIDAD INTERNA (JWE)
# =============================================================================
#jwe:
#  internal:
#    # Secreto compartido con el Gateway para la comunicación interna.
#    secret: "jass-microservices-internal-secret-2025-change-in-production"
#    # Tiempo de expiración del token en segundos (86400s = 24 horas)
#    expiration: 86400
#    # Emisor del token (debe coincidir con el del gateway)
#    issuer: "ms-users-internal"
#    # Audiencia del token (debe coincidir con la configurada en el gateway)
#    audience: "jass-microservices"

cors:
     allowed-origins: "*"
     allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
     allowed-headers: "*"
     allow-credentials: true
     max-age: 3600


# =============================================================================
# CONFIGURACIÓN DE DOCUMENTACIÓN (OpenAPI/Swagger)
# =============================================================================
springdoc:
     api-docs:
          path: /v3/api-docs
          enabled: true

     swagger-ui:
          path: /swagger-ui.html
          try-it-out-enabled: true
          operations-sorter: method
          tags-sorter: alpha
          display-request-duration: true
          disable-swagger-default-url: true

     show-actuator: false

 
# =============================================================================
# INFORMACIÓN DE LA APLICACIÓN
# =============================================================================
app:
     name: Microservicio de Usuarios y Autenticación
     description: Microservicio para gestión de Usuarios y Autenticación del Sistema JASS Digital
     version: 2.0.0
     organization: Valle Grande

# =============================================================================
# CONFIGURACIÓN DE CLIENTES EXTERNOS (OTROS MICROSERVICIOS)
# =============================================================================
microservices:
     users:
          name: ms-users
          base-url: ${MS_USERS_URL:https://lab.vallegrande.edu.pe/jass/ms-users}
          endpoints:
               admins: /internal/organizations/{organizationId}/admins
               users: /internal/organizations/{organizationId}/users
               clients: /internal/organizations/{organizationId}/clients
               userById: /internal/users/{userId}
               create-admin: /internal/organizations/{organizationId}/create-admin
               validate: /internal/users/validate
               organizationById: /internal/organizations/{organizationId}
          timeout:
               connection: 10000
               read: 10000
               write: 10000

# =============================================================================
# CONFIGURACIÓN DE ACTUATOR (MONITOREO)
# =============================================================================
management:
     endpoints:
          web:
               exposure:
                    include: health,info,metrics,env
               base-path: /actuator

     endpoint:
          health:
               show-details: when-authorized
               show-components: always

     info:
          env:
               enabled: true
          git:
               mode: full

# =============================================================================
# CONFIGURACIÓN DE LOGGING
# =============================================================================
logging:
     level:
          root: INFO
          pe.edu.vallegrande: DEBUG
          org.springframework.data.mongodb: WARN
          org.mongodb.driver: WARN
          reactor.netty: DEBUG
          org.springframework.web.reactive.function.client: DEBUG
          org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

     pattern:
          console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
          file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

     file:
          name: logs/users-authentication.log
          max-size: 10MB
          max-history: 10


## =============================================================================
## CONFIGURACIÓN DEL LOGGING
## =============================================================================
#loggin:
#  level:
#    root: INFO
#    pe.edu.vallegrande: DEBUG
#    org.springframework.data.mongodb: DEBUG
#    reactor.netty: INFO
#    org.keycloack: DEBUG
#
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# =============================================================================
# CONFIGURACIÓN DE VALIDACIÓN
# =============================================================================
validation:
     user:
          code:
               prefix: USR
               length: 7
          document:
               dni-length: 8
               passport-min-length: 6
               passport-max-length: 12

# =============================================================================
# CONFIGURACIÓN ESPECÍFICA POR AMBIENTE
# =============================================================================
---
spring:
     config:
          activate:
               on-profile: dev

logging:
     level:
          pe.edu.vallegrande: DEBUG
          org.springframework.data.mongodb: DEBUG

---
spring:
     config:
          activate:
               on-profile: prod

logging:
     level:
          root: WARN
          pe.edu.vallegrande: INFO

server:
     error:
          include-stacktrace: never
          include-message: never
